### Toy Problem of Markov Process

There are four income classes in one country (old money, middle class, poor, homeless). Their proportions change every year, but this change fits the Markov process and the specific change can be described by a transition matrix. 

**Q:what is the proportion in the end?**

In [4]:
import numpy as np
i=0
n=20
#income class:The proportion in society of old money， middle class， poor， homeless
x = np.array([
    [0.70],
    [0.15],
    [0.05],
    [0.10]])  # the current state vector
P = 0.85*np.array([
    [0., 1., 0.5, 1],
    [0.5, 0, 0.5, 0.0],
    [0.5, 0, 0., 0.0],
    [0.0, 0, 0., 0.0]
]) + 0.15*0.25*np.ones([4,4]) # transition matrix
#**input your code**#



#*******************#
print(x)

[[0.0375 0.8875 0.4625 0.8875]
 [0.4625 0.0375 0.4625 0.0375]
 [0.4625 0.0375 0.0375 0.0375]
 [0.0375 0.0375 0.0375 0.0375]]


change the initial value

In [14]:
x = np.array([
    [0.1],
    [0.2],
    [0.4],
    [0.3]])  
#**input your code**#



#*******************#
print(x)

[[0.25119234]
 [0.25176337]
 [0.24880766]
 [0.24823663]]


changee matrix

In [ ]:
P = np.array([
    [0.8, 0.15, 0.00, 0.05],
    [0.05, 0.8, 0.15, 0.00],
    [0.00, 0.05, 0.8, 0.15],
    [0.15, 0.00, 0.05, 0.8]
])
#**input your code**#



#*******************#
print(x)

### Conclusion

1.In most cases, no matter what the initial state is, the final state will converge to a steady state.


$$\vec{x}_{t+1}=P\vec{x}_t$$

2.If P is a constant matrix, $\vec{x}_{t+1}$ is only related to $\vec{x}_t=(a1,a2,a3,a4)^T$.

i.e. An information state $\vec{x}_t$(a.k.a. Markov state) contains all useful information from the history $\vec{x}_1,\vec{x}_2,...,\vec{x}_{t-1}$.

i.e.the four variable $(a1,a2,a3,a4)^T$ is the full observability of state

i.e. Once the state $\vec{x}_t$ is known, the history $\vec{x}_1,\vec{x}_2,...,\vec{x}_{t-1}$ may be thrown away

In other word, the state $\vec{x}_t=(a1,a2,a3,a4)^T$ is a suffcient statistic of the future (4 × 1 column vectors$\vec{x}_{t+1}$).


### Further Reading
[Another example about pagerank and it has interactive illustration that can help you understand in deep](http://immersivemath.com/ila/ch10_eigen/ch10.html)

    Example 10.2: Simpliffied Pagerank
    How does Google rank web pages? In this example, we will look at a simplified model for ranking web pages. The main idea is that a web page has a higher rank if many pages (with high rank) links to this page. The problem is recursive. In order to calculate the rank of one page, you need to know the ranks of the other pages. Another way to look at this is to think of a person that randomly clicks on one of the links of a homepage. After random browsing, the page rank is the probability that you are on a certain homepage. In order to connect all homepages one has the idea that with a small probability (say 15 percent) one jumps to a totally random homepage. Let's look at a toy example. Assume that there are four homepages on the internet, 1 - 'Immersive Math', 2 - 'Linear Algebra', 3 - 'Boolean Algebra' and 4 - 'Boring Algebra'.
    ...(see at the above website)


For some cases where the final state does not converge, We can invoke the [Perron-Frobenius theorem](http://en.wikipedia.org/wiki/Perron-Frobenius_theorem) of matrix in the analysis of the convergence of the Pagerank algorithm.

With PF theorem, we can conclude that the Pagerank with damping factor, under the assumption that all eigenvalues of P are distinct, converges to an eigenvector corresponding to the largest eigenvalue $\lambda_1$ = 1.